### ISSUE TITLE
[Feature request] client  feature list

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#561]
List the requirements under the client(列举在客户端下的需求):
如果有其他新增的可在下方回复列举。
```[tasklist]
### Tasks
- [ ] 【sidebar】'codeTheme'修改成图标后展示
- [ ] 自定义安装页面
- [ ] 版本自动更新检测
- [ ] 收集所有*.md文件，并注册注册表改变logo
- [ ] 全屏功能（客户端全屏）
- [ ] 【menu】快捷键，联系我们，更新日志
- [ ] [menu] export, ,theme切换( light or dark)showToolbar切换( true or false),classicBr，标题的样式，功能能在客户端的菜单l栏上操作
```
