### ISSUE TITLE
双栏编辑模式下，表格快捷操作时，双击会出现BUG

### ISSUE THREAD

**Issue by xuliuzhu1834** [Tencent/cherry-markdown#668]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.sheincorp.cn/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

在右侧快捷操作中，在单元格内双击后随便输入，均会出现表格消失的情况
![image](https://i.ibb.co/w0n2QvV/image.png)
![image](https://i.ibb.co/8M8KXqy/image.png)

你的示例中就可以复现

### Contributing

None
```[tasklist]
### Tasks
- [ ] https://github.com/Tencent/cherry-markdown/issues/662
```

**Comment by RSS1102** [comment]
好的，这里是有点不少问题。谢谢反馈。

**Comment by sunsonliu** [comment]
已修复并提交到dev分支，感谢反馈，也欢迎体验哈~
