### ISSUE TITLE
[Bug Report] 有序列表、无序列表、checklist 在 defaultModel='previewOnly' 时可编辑

### ISSUE THREAD

**Issue by magicfold** [Tencent/cherry-markdown#777]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

有序列表、无序列表、checklist 在 defaultModel='previewOnly' 时可编辑，应该禁止编辑

### Contributing

None

**Comment by magicfold** [comment]
已解决，将 previewer.enablePreviewerBubble 置为 false 即可
