### ISSUE TITLE
[Client] V1 路线图 (Roadmap)

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#970]
### Clear and concise description of the problem or idea.

目前将 client 从 electron 迁移到了 tauri 进行实现, 见: https://github.com/Tencent/cherry-markdown/pull/969

当前功能主要需要实现有:
- [ ] 优化save保存文件操作状态 — 当未修改或者已保存时进行​disabled，当文件被改变时进行回访。
- [ ] 添加页脚 — 显示当前打开文件路径。
- [ ] 添加title —  显示打开文件名。
- [ ] link跳转 —  网页。
- [ ] 图片展示 — 展示索引本地图片文件。
- [ ] 保存文件状态提示 — 添加明显文件保存和为保存状态显示(具体实现方式待定)。
- [ ] 新建文件/打开新文件时 未保存文件保护 — 增加二次弹窗提示。
- [ ] Window menu — 添加 about=>添加客户端说明、商标、版本信息顿和 repo 地址等。
- [ ] 调整窗口合适大小。
- [ ] 屏蔽右键 tauri 客户端操作。
- [ ] 增加部分快捷键用来处理文件 — 目前主要实现对于文件操作，如: 保存，另存为，新文件等。
- [ ] 优化精简toolbar。

---
未来预期要实现功能(待定)。
- [ ] 开屏 loading。
- [ ] 增加面板展示文件目录 — (参考 可参考 vscode 客户端 和 https://github.com/lgou2w/HoYo.Gacha) 这里目前是对于已打开文件路径记录,(如果不存在文件移除并添加提示)。
- [ ] Window下右键/默认使用客户端打开md文件以及 `*.md` 文件图标注册表注册。
- [ ] 对于文件面板文件进行 标记tag分类 filter 展示。(创建tag，标记tag，未分类)。
- [ ] 改变客户端主题和cherry-markdown一致。
- [ ] 图片点击放大预览。
- [ ] 全屏模式切换 —— 目前 cherry-markdown 只有网页内全屏不能支持此功能，需自行扩展客户端内全屏的打开和关闭。
- [ ] 插件化自定义主题。
- [ ] 自定义nsis安装页面。
- [ ] mac认证（待定）。

---
**如有其他功能欢迎添加和讨论。**

**Comment by RSS1102** [comment]
Related https://github.com/Tencent/cherry-markdown/issues/1077

**Comment by yanhuixie** [comment]
大佬们不妨评估一下  https://github.com/yanhuixie/cherry-markdown-desktop  这个版本是否符合发展路径？
目前实现了Tab页、亮色/暗色主题、单例模式、命令行启动打开md、explorer打开md集成。

**Comment by Doner178** [comment]
Another
